language: node_js
node_js:
  - 8.12
cache:
  directories:
    - node_modules
before_script:
  - npm install
branches: 
  only:
    - master
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "travis-build-demo"
